# Generated by Django 5.1.3 on 2024-12-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='trade_amount',
            field=models.FloatField(default=0.001),
            preserve_default=False,
        ),
    ]
