# Generated by Django 5.1.3 on 2024-12-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_strategy_trade_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='time_frame',
            field=models.CharField(default='5m', max_length=20),
            preserve_default=False,
        ),
    ]
