# Generated by Django 5.1.3 on 2024-12-28 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_strategy_time_frame'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy',
            old_name='rsi_overbought',
            new_name='rsi_period',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='rsi_oversold',
        ),
    ]
